spring.application.name=demo1

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/lab_db
spring.datasource.username=postgres
spring.datasource.password=022070


mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl